### ISSUE TITLE
[testnet] Error creating keybase account

### ISSUE THREAD

**Issue by dffffffff** [bluzelle/curium#163]
Virtualization: kvm
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 4.19.0-14-amd64
Architecture: x86-64

Branch: oracle
name: BluzelleService
server_name: blzd
client_name: blzcli
version: productionMainNetAlfa-74-g6ea03ed
commit: 6ea03ed92d0fac3f1334156dbae30b7118b3c5c9
build_tags: ledger,faucet,cosmos-sdk v0.39.1
go: go version go1.15.6 linux/amd64

How to did this error occur:
After shutting down blzd to make a config change in config.toml, i restarted blzd which will sign about 10 blocks then crash with the following output.

I have left the environment in the same state. Restarting blzd will reproduce the error.

```E[2021-02-18|22:04:00.597] Error creating keybase account               err="unsupported key type"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10bf849]

goroutine 2177 [running]:
github.com/bluzelle/curium/x/oracle.BroadcastOracleMessages(0xc0441f3a50, 0x1, 0x1, 0xc000c1c000, 0x1, 0xc0441f3a50, 0x0)                                                                                      
        /home/blzd/go/src/github.com/bluzelle/curium/x/oracle/feeder.go:188 +0x149
github.com/bluzelle/curium/x/oracle.sendPreflightMsgs(0xc044212820, 0x1, 0x1, 0xc000c1c000, 0x1, 0x1)
        /home/blzd/go/src/github.com/bluzelle/curium/x/oracle/feeder.go:128 +0x2cf
github.com/bluzelle/curium/x/oracle.GetValueAndSendProofAndVote(0x172f900, 0xc000f4ded0, 0x172f900, 0xc000f4dee0, 0x172f900, 0xc000f4def0, 0x172f900, 0xc000f4df00, 0x172f900, 0xc000f4de20, ...)              
        /home/blzd/go/src/github.com/bluzelle/curium/x/oracle/feeder.go:50 +0x145
github.com/bluzelle/curium/x/oracle.RunFeeder.func1()
        /home/blzd/go/src/github.com/bluzelle/curium/x/oracle/feeder.go:36 +0xac
github.com/robfig/cron/v3.FuncJob.Run(0xc03edd7f20)
        /home/blzd/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x25
github.com/robfig/cron/v3.(*Cron).startJob.func1(0xc0000b2f00, 0x17203e0, 0xc03edd7f20)
        /home/blzd/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x65
created by github.com/robfig/cron/v3.(*Cron).startJob
        /home/blzd/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x73```

**Comment by scottburch** [comment]
That is due to the oracle stuff.  To fix that, there must be some configuration added to the app.toml file.  Can be any account. This account must have enough tokens to create a transaction, but will not be charged for transactions.


oracle-user-address = "bluzellexxxxx"
oracle-user-mnemonic = "xxx xxx xxx..."
