### ISSUE TITLE
keyring interaction caues panic with go1.16.4

### ISSUE THREAD

**Issue by dffffffff** [bluzelle/curium#168]
version: productionMainNetAlfa-146-g9da3087
commit: 9da30870716a5e7589fab64dd8e9c63b26a47f43
build_tags: ledger,faucet,cosmos-sdk v0.39.1
go: go version go1.16.4 linux/amd64

```
blzcli keys add key_name
panic: crypto/hmac: hash generation function does not produce unique values

goroutine 1 [running]:
crypto/hmac.New(0xc000228eb0, 0xc000fae5a0, 0x4, 0x8, 0x0, 0x8)
        /usr/local/go/src/crypto/hmac/hmac.go:143 +0x370
github.com/dvsekhvalnov/jose2go/kdf.DerivePBKDF2(0xc000fae5a0, 0x4, 0x8, 0xc00010b7a0, 0x1f, 0x30, 0x2000, 0x80, 0x14029f8, 0xc000f10980, ...)
        /home/blzd/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/kdf/pbkdf2.go:15 +0xad
github.com/dvsekhvalnov/jose2go.(*Pbse2HmacAesKW).WrapNewKey(0xc0005723c0, 0x100, 0xf53820, 0xc000f7b9d0, 0xc000f94810, 0x203001, 0x100, 0x7fab11beffff, 0x400, 0x7fab11a6d900, ...)
        /home/blzd/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/pbse2_hmac_aeskw.go:50 +0x439
github.com/dvsekhvalnov/jose2go.encrypt(0xc0002cc5a0, 0x114, 0x120, 0xc000f94810, 0xf53820, 0xc000f7b9d0, 0xc0002cc6b4, 0xc, 0x0, 0xc0002cc5a0)
        /home/blzd/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/jose.go:305 +0x20a
github.com/dvsekhvalnov/jose2go.EncryptBytes(0xc0002cc5a0, 0x114, 0x120, 0x10efcf2, 0x12, 0x10e4ef8, 0x7, 0xf53820, 0xc000f7b9d0, 0xc0002293d8, ...)
        /home/blzd/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/jose.go:222 +0x32f
github.com/dvsekhvalnov/jose2go.Encrypt(...)
        /home/blzd/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/jose.go:187
github.com/99designs/keyring.(*fileKeyring).Set(0xc000f944b0, 0xc000fae400, 0xe, 0xc0002d02d0, 0x6a, 0xe9, 0x0, 0x0, 0x0, 0x0, ...)
        /home/blzd/go/pkg/mod/github.com/99designs/keyring@v1.1.3/file.go:143 +0x319
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x12df648, 0x12df640, 0xc000f7b710, 0x1, 0x1, 0xc000f7b720, 0x1, 0x1, 0x1402b38, 0xc000f944b0, ...)
        /home/blzd/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:473 +0x218
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeLocalKey(0x12df648, 0x12df640, 0xc000f7b710, 0x1, 0x1, 0xc000f7b720, 0x1, 0x1, 0x1402b38, 0xc000f944b0, ...)
        /home/blzd/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:464 +0x193
github.com/cosmos/cosmos-sdk/crypto/keys.baseKeybase.CreateAccount(0x12df648, 0x12df640, 0xc000f7b710, 0x1, 0x1, 0xc000f7b720, 0x1, 0x1, 0x13f4550, 0xc00002f310, ...)
        /home/blzd/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keybase_base.go:171 +0x1a2
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.CreateAccount(...)
        /home/blzd/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:106
github.com/cosmos/cosmos-sdk/client/keys.RunAddCmd(0xc000f83b80, 0xc000f7ad10, 0x1, 0x1, 0x1410818, 0xc00002f2c0, 0xc000f51260, 0xc000229c48, 0x5edd97)
        /home/blzd/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/client/keys/add.go:273 +0x743
github.com/cosmos/cosmos-sdk/client/keys.runAddCmd(0xc000f83b80, 0xc000f7ad10, 0x1, 0x1, 0x0, 0x0)
        /home/blzd/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/client/keys/add.go:99 +0x170
github.com/spf13/cobra.(*Command).execute(0xc000f83b80, 0xc000f7acf0, 0x1, 0x1, 0xc000f83b80, 0xc000f7acf0)
        /home/blzd/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f0e000, 0xc000229e70, 0x8692e5, 0xc000f0e000)
        /home/blzd/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/blzd/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000f0e000, 0x12e2018, 0x2, 0xc00009a390)
        /home/blzd/go/pkg/mod/github.com/tendermint/tendermint@v0.33.9/libs/cli/setup.go:89 +0x3c
main.main()
        /home/blzd/go/src/github.com/bluzelle/curium/cmd/blzcli/main.go:82 +0x591
```

Other references.

https://github.com/golang/go/issues/45252

https://github.com/anthraxx/alicloud-vault/commit/8d1f68a1f0b3cb16b786f82f028b95fe7200bb14

**Comment by scottburch** [comment]
Yep.  I found the same thing.  Works with the new Curium.  Thanks for documenting.
