### ISSUE TITLE
Panic when fetching oracle source 

### ISSUE THREAD

**Issue by dffffffff** [bluzelle/curium#169]
```
version: productionMainNetAlfa-146-g9da3087
commit: 9da30870716a5e7589fab64dd8e9c63b26a47f43
build_tags: ledger,faucet,cosmos-sdk v0.39.1
go: go version go1.15.12 linux/amd64
```

Newly created validator on bluzelleTestNetPublic-22 (bluzellevaloper12hp4592hy4j5x733z2ce6eqq9e8rsmjp7h6kmy) crashes with the following logs when fetching oracle source

```
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.000] Oracle feeder run                            Valcons=bluzellevalcons1mfllfqcd9wl86plrgd584t69lr555rtv67jv4q
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.001] Oracle fetching from sources                 count=46
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.854] Error fetching oracle source                 name=nomics-blz-in-usd err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.862] Error fetching oracle source                 name=nomics-eth-in-usd err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.865] Error fetching oracle source                 name=nomics-btc-in-usd err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.884] Error fetching oracle source                 name=nomics-btc-in-usdt err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.885] Error fetching oracle source                 name=nomics-blz-in-usdc err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.891] Error fetching oracle source                 name=nomics-eth-in-usdt err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.894] Error fetching oracle source                 name=nomics-eth-in-usdc err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.923] Error fetching oracle source                 name=nomics-eth-in-btc err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.924] Error fetching oracle source                 name=nomics-blz-in-eth err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.925] Error fetching oracle source                 name=nomics-blz-in-usdt err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.931] Error fetching oracle source                 name=nomics-btc-in-usdc err="invalid character 'A' looking for beginning of value"
May 10 14:31:00 validator blzd[8821]: I[2021-05-10|14:31:00.937] Error fetching oracle source                 name=nomics-blz-in-btc err="invalid character 'A' looking for beginning of value"
May 10 14:31:03 validator blzd[8821]: I[2021-05-10|14:31:03.944] Executed block                               module=state height=25491 validTxs=3 invalidTxs=0
May 10 14:31:03 validator blzd[8821]: I[2021-05-10|14:31:03.953] Committed state                              module=state height=25491 txs=3 appHash=1C97802C805909A81508CE0801BF4FF3EDD92F6FBCC9B4
720E3EEBC8B851D5A4
May 10 14:31:09 validator blzd[8821]: I[2021-05-10|14:31:09.645] Executed block                               module=state height=25492 validTxs=1 invalidTxs=0
May 10 14:31:09 validator blzd[8821]: I[2021-05-10|14:31:09.653] Committed state                              module=state height=25492 txs=1 appHash=0C309B9A2F5568CCF710497281F41F513010F36E92DE78
B803474CA654EBBA05
May 10 14:31:10 validator blzd[8821]: I[2021-05-10|14:31:10.040] Sending oracle proof messages                count=46
May 10 14:31:10 validator blzd[8821]: E[2021-05-10|14:31:10.040] Error creating keybase account               err="unsupported key type"
May 10 14:31:10 validator blzd[8821]: panic: runtime error: invalid memory address or nil pointer dereference
May 10 14:31:10 validator blzd[8821]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10aae0f]
May 10 14:31:10 validator blzd[8821]: goroutine 1546 [running]:
May 10 14:31:10 validator blzd[8821]: github.com/bluzelle/curium/x/oracle.BroadcastOracleMessages(0xc003200800, 0x2e, 0x40, 0xc000402000, 0x2, 0x2, 0xa)
May 10 14:31:10 validator blzd[8821]: #011/home/blzd/go/src/github.com/bluzelle/curium/x/oracle/feeder.go:231 +0x18f
May 10 14:31:10 validator blzd[8821]: github.com/bluzelle/curium/x/oracle.sendPreflightMsgs(0xc00016d000, 0x2e, 0x45, 0xc000402000, 0x2e, 0x45)
May 10 14:31:10 validator blzd[8821]: #011/home/blzd/go/src/github.com/bluzelle/curium/x/oracle/feeder.go:152 +0x3f6
May 10 14:31:10 validator blzd[8821]: github.com/bluzelle/curium/x/oracle.GetValueAndSendProofAndVote(0x1755e00, 0xc00056ce90, 0x1755e00, 0xc00056cdb0, 0xc000402000, 0x1774b00, 0xc000569100, 0x177
7c00, 0xc00025c180, 0xc000402000, ...)
May 10 14:32:01 validator blzd[8832]: #011/home/blzd/go/src/github.com/bluzelle/curium/x/oracle/feeder.go:61 +0x225
May 10 14:32:01 validator blzd[8832]: github.com/bluzelle/curium/x/oracle.RunFeeder.func1()
May 10 14:32:01 validator blzd[8832]: #011/home/blzd/go/src/github.com/bluzelle/curium/x/oracle/feeder.go:46 +0x288
May 10 14:32:01 validator blzd[8832]: github.com/robfig/cron/v3.FuncJob.Run(0xc003512d80)
May 10 14:32:01 validator blzd[8832]: #011/home/blzd/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x25
May 10 14:32:01 validator blzd[8832]: github.com/robfig/cron/v3.(*Cron).startJob.func1(0xc0016934a0, 0x17467e0, 0xc003512d80)
May 10 14:32:01 validator blzd[8832]: #011/home/blzd/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x65
May 10 14:32:01 validator blzd[8832]: created by github.com/robfig/cron/v3.(*Cron).startJob
May 10 14:32:01 validator blzd[8832]: #011/home/blzd/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x73
May 10 14:32:01 validator systemd[1]: blzd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 10 14:32:01 validator systemd[1]: blzd.service: Failed with result 'exit-code'.
```

**Comment by scottburch** [comment]
Probably due to the oracle account not existing prior to starting the validator.  Needs to be fixed.

**Comment by scottburch** [comment]
Need to add a oracle user to the app.toml for the oracle.  Transactions are free, but the account needs to have enough blz to complete transactions.  It just won't be charged.

oracle-user-address = "bluzelle1qw2r0u8tpc3ussvuvqvqmkc2hqhq7awu8zhque"
oracle-user-mnemonic = "xxx xxx xxx xxx"
